import { DM_Sans, Lexend_Tera } from "next/font/google";

import "./globals.css";
import Footer from "@/components/shared/Footer";
import Header from "@/components/shared/Header";

const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

const lexendTera = Lexend_Tera({
  subsets: ['latin'],
  weight: ['400'], 
  variable: '--font-lexend-tera',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${dmSans.variable} ${lexendTera.variable} h-full antialiased ` }>
  <body className="min-h-full flex flex-col">

    <Header />

    {children}

    <Footer />

  </body>
</html>
  );
}
